---
kind: ConfigMap
apiVersion: v1
metadata:
  name: master-config
  namespace: system
data:
  config.yaml: |
    server:
      http:
        addr: 0.0.0.0:8000
        timeout: 1s
      grpc:
        addr: 0.0.0.0:9000
        timeout: 1s
    data:
      database:
        driver: mysql
        source: root:123456@tcp(192.168.116.57:30001)/prom
      redis:
        addr: 127.0.0.1:6379
        read_timeout: 0.2s
        write_timeout: 0.2s
    
    env:
      name: "prometheus-manager-master"
      version: "v0.0.1"
      namespace: "prometheus-manager"
      metadata:
        env: "dev"
        description: "Kratos Layout App"
    
    trace:
      endpoint: http://127.0.0.1:14268/api/traces
    
    registrar:
      etcd:
        endpoints:
          - localhost:20000
          - localhost:20002
          - localhost:20004
        key_file: "xxx"
        cert_file: "xxx"
        trusted_ca_file: "xxx"
    
    push_strategy:
      interval: 10s
      dir: /tmp/prometheus-manager
      enable: false
      nodes:
        - server_name: "prometheus-manager-node"
          timeout: 1s
          network: "grpc" # grpc, http, https
    
    kafka:
      alert_topic: "prometheus-manager-node-alert"
      endpoints:
        - "localhost:9092"
        - "localhost:9093"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: node-config
  namespace: system
data:
  config.yaml: |
    server:
      http:
        addr: 0.0.0.0:8000
        timeout: 1s
      grpc:
        addr: 0.0.0.0:9000
        timeout: 1s
    
    trace:
      endpoint: http://127.0.0.1:14268/api/traces
    
    strategy:
      load_interval: 10s
      reload_interval: 10s
      reload_path: "http://localhost:9090/-/reload"
      enable: false
      # 目录为绝对路径或者相对configs路径
      path:
        - "rule_temp"
        - "rule_temp/apache"
        - "rule_temp/core_dns"
    
    prom_datasources:
      - name: "prometheus-node"
        type: "prometheus"
        url: "http://localhost:9090"
        access: ""
    
    env:
      name: "prometheus-manager-node"
      version: "v0.0.1"
      namespace: "prometheus-manager"
      metadata:
        description: "Kratos Layout App"
        env: "local"
    
    registrar:
      etcd:
        endpoints:
          - localhost:20000
          - localhost:20002
          - localhost:20004
        key_file: "xxx"
        cert_file: "xxx"
        trusted_ca_file: "xxx
    
    kafka:
      alert_topic: "prometheus-manager-node-alert"
      endpoints:
        - "localhost:9092"
        - "localhost:9093"
