apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: system
  labels:
    apps.prometheus.manager/name: prometheus-manager-master
spec:
  selector:
    matchLabels:
      apps.prometheus.manager/name: prometheus-manager-master
  replicas: 1
  template:
    metadata:
      labels:
        apps.prometheus.manager/name: prometheus-manager-master
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
            - /prometheus-manager-master
          args:
            - --conf=/config/config.yaml
          image: controller:latest
          name: master
          securityContext:
            allowPrivilegeEscalation: false
          #          // TODO: @梧桐 Supplemental Health Screening Services
          #          livenessProbe:
          #            httpGet:
          #              path: /healthz
          #              port: 8081
          #            initialDelaySeconds: 15
          #            periodSeconds: 20
          #          readinessProbe:
          #            httpGet:
          #              path: /readyz
          #              port: 8081
          #            initialDelaySeconds: 5
          #            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          volumeMounts:
            - mountPath: /config
              name: prometheus-manager-master-config
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: prometheus-manager-master
      terminationGracePeriodSeconds: 10
      volumes:
        - name: prometheus-manager-master-config
          configMap:
            name: prometheus-manager-master-config

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node
  namespace: system
  labels:
    apps.prometheus.manager/name: prometheus-manager-node
spec:
  selector:
    matchLabels:
      apps.prometheus.manager/name: prometheus-manager-node
  template:
    metadata:
      labels:
        apps.prometheus.manager/name: prometheus-manager-node
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
            - /prometheus-manager-node
          args:
            - --conf=/config/config.yaml
          image: controller:latest
          name: node
          securityContext:
            allowPrivilegeEscalation: false
          #          // TODO: @梧桐 Supplemental Health Screening Services
          #          livenessProbe:
          #            httpGet:
          #              path: /healthz
          #              port: 8081
          #            initialDelaySeconds: 15
          #            periodSeconds: 20
          #          readinessProbe:
          #            httpGet:
          #              path: /readyz
          #              port: 8081
          #            initialDelaySeconds: 5
          #            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          volumeMounts:
            - mountPath: /config
              name: prometheus-manager-node-config
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: prometheus-manager-node
      terminationGracePeriodSeconds: 10
      volumes:
        - name: prometheus-manager-node-config
          configMap:
            name: prometheus-manager-node-config
