apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: system
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      apps.prometheus.manager/name: prometheus-manager-mysql
  template:
    metadata:
      labels:
        apps.prometheus.manager/name: prometheus-manager-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.33
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456" # TODO: set your password
          imagePullPolicy: Always
          ports:
            - containerPort: 3306