---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: system
  labels:
    apps.prometheus.manager/name: prometheus-manager-mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30001
  selector:
    apps.prometheus.manager/name: prometheus-manager-mysql
  type: NodePort
  sessionAffinity: ClientIP   