server:
  name: prometheus-manager_server
  mode: release
  matadata:
    version: 1.0.0
    description: prometheus-manager_server is a prometheus manager server
  http:
    host: '0.0.0.0'
    port: 8080

data:
  mysql:
    dsn: root:12345678@tcp(localhost:3306)/prom?charset=utf8mb4&parseTime=True&loc=Local
    debug: true

kafka:
  # enable: true
  endpoints:
    - "localhost:9092"

alert:
  # enable: true
  topic: "prometheus-manager-node-alert"