info:
    title: github.com/aide-cloud/gin-plus
    version: v0.3.1
openapi: 3.1.3
paths:
    /api/alert/hook:
        post:
            operationId: PostHook
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
